### ISSUE TITLE
Doesn't work with nested entry points

### ISSUE THREAD

**Issue by Arithmomaniac** [webschik/typescript-polyfills-generator#4]
Running the standard setup with entry points in webpack.config that look like follows:

```
entry: {
   licenseIndex: './Static/License/Index.ts',
   licenseInvalidLicense: './Static/License/InvalidLicense.ts',
   settingsIndex: './Static/Settings/Index.ts',
    /*...*/
},
```

Gives the following error:

> ERROR in ./Static/License/InvalidLicense.ts
> Module build failed (from ./node_modules/ts-loader/index.js):
> Error: Failed to load customTransformers from "C:\_SOURCECODE\MyApp\src\MyApp.Web\webpack.custom-transformers.js": Cannot find module '../data/built-ins.json'
>     at successfulTypeScriptInstance (C:\_SOURCECODE\MyApp\src\MyApp.Web\node_modules\ts-loader\dist\instances.js:69:19)
>     at Object.getTypeScriptInstance (C:\_SOURCECODE\MyApp\src\MyApp.Web\node_modules\ts-loader\dist\instances.js:34:12)
>     at Object.loader (C:\_SOURCECODE\MyApp\src\MyApp.Web\node_modules\ts-loader\dist\index.js:17:41)

**Comment by webschik** [comment]
it's fixed in v0.2.0
